### ISSUE TITLE
Issues in foot terminal

### ISSUE THREAD

**Issue by squishram** [sphamba/smear-cursor.nvim#3]
I love the look of this plugin - I'm just wondering if it's somehow optimised for X? In foot (wayland native terminal), there is a "ghost" the cursor on the line above when moving along a line. Thanks for your work!

**Comment by sphamba** [comment]
I did a quick test in `foot` and did not notice a behavior that differs from my current terminal. When moving diagonally from one line to another, the dark gost is (sadly) expected due to the way the smear is draw. However, it should not appear when moving on a straight line. Is it the case for you?

**Comment by squishram** [comment]
![image](https://github.com/user-attachments/assets/31b2c8c3-219e-47f6-ae90-9ffb51b4143d)
Screencapped just as I was pressing `w`. You can see that there is a duplicate of the cursor above the line. Not sure if this is an issue with how I've configured `foot` or something else... but it's consistent with horizontal movement. Curious that you haven't got the same issue, interested in whether anyone is seeing the same!

**Comment by sphamba** [comment]
Perhaps fixed by PR #21? (merged)
